"""Add urgency column to measure_assignments

Revision ID: 61c70022f2e6
Revises: 85bf436b1b65
Create Date: 2025-08-26 05:05:45.658400+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c70022f2e6'
down_revision = '85bf436b1b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgency', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure_assignments', schema=None) as batch_op:
        batch_op.drop_column('urgency')

    # ### end Alembic commands ###
