"""sync schema with models (notifications, assistance, etc.)

Revision ID: 85bf436b1b65
Revises: 74dbe14596f9
Create Date: 2025-08-22 09:10:10.142345+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85bf436b1b65'
down_revision = '74dbe14596f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Make this migration idempotent by checking what exists
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Drop temporary table only if it exists
    if '_alembic_tmp_assignment_steps' in inspector.get_table_names():
        op.drop_table('_alembic_tmp_assignment_steps')
    
    # Get table names
    table_names = inspector.get_table_names()
    
    # Get column names for each table (only if table exists)
    assignment_steps_cols = [c['name'] for c in inspector.get_columns('assignment_steps')] if 'assignment_steps' in table_names else []
    measure_assignments_cols = [c['name'] for c in inspector.get_columns('measure_assignments')] if 'measure_assignments' in table_names else []
    measure_steps_cols = [c['name'] for c in inspector.get_columns('measure_steps')] if 'measure_steps' in table_names else []
    measures_cols = [c['name'] for c in inspector.get_columns('measures')] if 'measures' in table_names else []
    
    # assignment_steps: add step column if it doesn't exist
    if 'step' not in assignment_steps_cols and 'order_index' in assignment_steps_cols:
        with op.batch_alter_table('assignment_steps', schema=None) as batch_op:
            batch_op.add_column(sa.Column('step', sa.Integer(), nullable=True))
        op.execute("UPDATE assignment_steps SET step = order_index WHERE step IS NULL")
        with op.batch_alter_table('assignment_steps', schema=None) as batch_op:
            batch_op.alter_column('step', nullable=False)
            batch_op.drop_column('order_index')
    
    # measure_assignments: add date columns if they don't exist (only if table exists)
    if 'measure_assignments' in table_names:
        with op.batch_alter_table('measure_assignments', schema=None) as batch_op:
            if 'start_date' not in measure_assignments_cols:
                batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
            if 'end_date' not in measure_assignments_cols:
                batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
            # Drop old columns and indexes only if they exist
            try:
                if 'urgency' in measure_assignments_cols:
                    batch_op.drop_column('urgency')
            except:
                pass
            try:
                if 'timeframe_date' in measure_assignments_cols:
                    batch_op.drop_column('timeframe_date')
            except:
                pass
            try:
                if 'duration_days' in measure_assignments_cols:
                    batch_op.drop_column('duration_days')
            except:
                pass
    
    # measure_steps: add step column if it doesn't exist (only if table exists)
    if 'measure_steps' in table_names and 'step' not in measure_steps_cols and 'order_index' in measure_steps_cols:
        with op.batch_alter_table('measure_steps', schema=None) as batch_op:
            batch_op.add_column(sa.Column('step', sa.Integer(), nullable=True))
        op.execute("UPDATE measure_steps SET step = order_index WHERE step IS NULL")
        with op.batch_alter_table('measure_steps', schema=None) as batch_op:
            batch_op.alter_column('step', nullable=False)
            batch_op.drop_column('order_index')
    
    # measures: add new columns and drop old ones (only if table exists)
    if 'measures' in table_names:
        with op.batch_alter_table('measures', schema=None) as batch_op:
            if 'measure_detail' not in measures_cols:
                batch_op.add_column(sa.Column('measure_detail', sa.Text(), nullable=True))
            if 'start_date' not in measures_cols:
                batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
            if 'end_date' not in measures_cols:
                batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
            # Drop old columns only if they exist
            try:
                if 'default_timeframe_date' in measures_cols:
                    batch_op.drop_column('default_timeframe_date')
            except:
                pass
            try:
                if 'default_duration_days' in measures_cols:
                    batch_op.drop_column('default_duration_days')
            except:
                pass
            try:
                if 'default_urgency' in measures_cols:
                    batch_op.drop_column('default_urgency')
            except:
                pass
            try:
                if 'description' in measures_cols:
                    batch_op.drop_column('description')
            except:
                pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('default_urgency', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('default_duration_days', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('default_timeframe_date', sa.DATE(), nullable=True))
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('measure_detail')

    with op.batch_alter_table('measure_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), nullable=False))
        batch_op.drop_column('step')

    with op.batch_alter_table('measure_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_days', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('timeframe_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('urgency', sa.INTEGER(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ma_measure_status'), ['measure_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ma_company_status'), ['company_id', 'status'], unique=False)
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('assignment_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), nullable=False))
        batch_op.drop_column('step')

    op.create_table('_alembic_tmp_assignment_steps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('step', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['measure_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
