"""sync schema with models (notifications, assistance, etc.)

Revision ID: 85bf436b1b65
Revises: 74dbe14596f9
Create Date: 2025-08-22 09:10:10.142345+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85bf436b1b65'
down_revision = '74dbe14596f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_assignment_steps')
    with op.batch_alter_table('assignment_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step', sa.Integer(), nullable=True))
    op.execute("UPDATE assignment_steps SET step = order_index")
    with op.batch_alter_table('assignment_steps', schema=None) as batch_op:
        batch_op.alter_column('step', nullable=False)
        batch_op.drop_column('order_index')

    with op.batch_alter_table('measure_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_ma_company_status'))
        batch_op.drop_index(batch_op.f('ix_ma_measure_status'))
        batch_op.drop_column('urgency')
        batch_op.drop_column('timeframe_date')
        batch_op.drop_column('duration_days')

    with op.batch_alter_table('measure_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step', sa.Integer(), nullable=True))
    op.execute("UPDATE measure_steps SET step = order_index")
    with op.batch_alter_table('measure_steps', schema=None) as batch_op:
        batch_op.alter_column('step', nullable=False)
        batch_op.drop_column('order_index')

    with op.batch_alter_table('measures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measure_detail', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.drop_column('default_timeframe_date')
        batch_op.drop_column('default_duration_days')
        batch_op.drop_column('default_urgency')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('default_urgency', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('default_duration_days', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('default_timeframe_date', sa.DATE(), nullable=True))
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('measure_detail')

    with op.batch_alter_table('measure_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), nullable=False))
        batch_op.drop_column('step')

    with op.batch_alter_table('measure_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_days', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('timeframe_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('urgency', sa.INTEGER(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ma_measure_status'), ['measure_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ma_company_status'), ['company_id', 'status'], unique=False)
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('assignment_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), nullable=False))
        batch_op.drop_column('step')

    op.create_table('_alembic_tmp_assignment_steps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('step', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['measure_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
