"""Add order column to measure_assignments

Revision ID: f1a2b3c4d5e6
Revises: 0e2db249053b
Create Date: 2025-11-06 10:32:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = '0e2db249053b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure_assignments', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
